data = [
'Barton Gellman',
'Garry Kasparov',
'Yuval Noah Harari',
'Ian Bremmer',
'Graeme Wood',
'Ricky Gervais',
'Eric Schmidt',
'Douglas Murray',
'Jay Garfield',
'Graeme Wood',
'Judd Apatow',
'David French',
'Morgan Housel',
'Peter Zeihan',
'Ian Bremmer',
'Oliver Burkeman',
'Marc Andreessen',
'Arthur C. Brooks',
'William MacAskill',
'Will Storr',
'Kieran Setiya',
'Jonah Goldberg',
'BJ Miller',
'Shoshana Berger',
'Yasmine Mohammed',
'Russ Roberts',
'Meg Smaker',
'Timothy Snyder',
'Neil deGrasse Tyson',
'Cal Newport',
'Erik Hoel',
'Roland Griffiths',
'Robert Waldinger',
'Martha Nussbaum',
'Bari Weiss',
'Michael Shellenberger',
'Renee DiResta',
'Matt Ridley',
'Alina Chan'
]